### ISSUE TITLE
t/get_public_keys.t fails with gnupg >= 2.4.1

### ISSUE THREAD

**Issue by eseyman** [bestpractical/gnupg-interface#11]
Ever since gnupg was upgraded to 2.4.1 in Fedora, I have been unable to build GnuPg-Interface.
The tests fail with:

t/get_public_keys.t .. 
1..3
ok 1
subkeys fail comparison; this is a known issue with GnuPG 1.0.1 at t/get_public_keys.t line 212.

**Comment by gregoa** [comment]
Looks a bit like https://github.com/bestpractical/gnupg-interface/pull/14

**Comment by eseyman** [comment]
This was fixed by upgrading to 1.0.4
